chore: bump version v0.26.0-rc4
HathorNetwork/hathor-wallet-mobile pull request #304
Opened 2023-07-26 12:17 UTC by tuliomir

### Acceptance Criteria
- Bump version to v0.26.0-rc4

### Security Checklist
- [X] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2023-07-27 15:01 UTC, alexruzenhack requested changes

2023-07-27 15:01 UTC, alexruzenhack commented on ios/HathorMobile.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 0.4.0;
When I started to work on the mobile we didn't change the `CURRENT_PROJECT_VERSION`. I'm wondering when it started to be changed and why?

2023-07-27 16:11 UTC, tuliomir commented on ios/HathorMobile.xcodeproj/project.pbxproj
Good catch, thanks!
It wasn't being updated on the last two release candidate versions, I missed it too.

2023-07-28 13:51 UTC, alexruzenhack approved these changes

2023-07-28 14:33 UTC, andreabadesso approved these changes

2023-07-28 16:03 UTC, merged