feat: add network settings flow stack
HathorNetwork/hathor-wallet-mobile pull request #346
Opened 2023-10-10 16:27 UTC by alexruzenhack

### Acceptance Criteria
- chore: add babel-plugin-module-resolver@5.0.0
- babel: configure @components and @screens module aliases
- feat: add NetworkSettingsFlowStack

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2023-10-11 16:50 UTC, andreabadesso requested changes

2023-10-11 16:50 UTC, andreabadesso commented on src/screens/NetworkSettings/index.js
> +}
```suggestion
/**
 * Copyright (c) Hathor Labs and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { NetworkSettingsFlowStack, NetworkSettingsFlowNav } from './NetworkSettingsFlowStack';

export {
  NetworkSettingsFlowStack,
  NetworkSettingsFlowNav,
};
```

2023-10-17 00:25 UTC, pedroferreira1 commented on src/screens/NetworkSettings/NetworkSettingsFlowStack.js
> +      initialRouteName='NetworkSetitngsDisclaimer'
```suggestion
      initialRouteName='NetworkSettingsDisclaimer'
```

2023-10-19 00:45 UTC, alexruzenhack commented on src/screens/NetworkSettings/index.js
> +}
- Add copyright: abe71c9d5fa5412a11994ce8416712ac2419d046

2023-10-19 00:45 UTC, alexruzenhack commented on src/screens/NetworkSettings/NetworkSettingsFlowStack.js
> +      initialRouteName='NetworkSetitngsDisclaimer'
- fix typo: 35a5b887be07c2db091c84dfdc4ccbd132511129

2023-10-20 13:14 UTC, andreabadesso approved these changes

2023-10-25 00:25 UTC, pedroferreira1 approved these changes

2023-10-25 22:01 UTC, merged