feat: add NetworkSettingsDisclaimerScreen
HathorNetwork/hathor-wallet-mobile pull request #347
Opened 2023-10-10 16:29 UTC by alexruzenhack

### Acceptance Criteria
- Add disclaimner screen

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2023-10-11 16:51 UTC, andreabadesso requested changes

2023-10-18 01:02 UTC, pedroferreira1 reviewed
I think I prefer the text to be more clear as a warning. I don't like having lot of text in yellow but maybe we could have a box with yellow background and this same text written inside the box in white or black. What do you think? Can you try something like that?

2023-10-19 15:27 UTC, alexruzenhack commented on src/screens/NetworkSettings/NetworkSettingsDisclaimerScreen.js
> +import React from 'react';
- Add copyright: 9a70ad4cdb85c5a1ee519174d3a65cdbb417cf92

2023-10-19 15:28 UTC, alexruzenhack commented
> I think I prefer the text to be more clear as a warning. I don't like having lot of text in yellow but maybe we could have a box with yellow background and this same text written inside the box in white or black. What do you think? Can you try something like that?

See if now it is better...

2023-10-19 15:35 UTC, alexruzenhack commented on src/screens/NetworkSettings/NetworkSettingsDisclaimerScreen.js
> +export const NetworkSettingsDislaimerNav = Symbol('NetworkSettingsDislaimer').toString();
- Fix typo on disclaimer names: 1078ed2302e99e0d406c104a503e3f84141b1933

2023-10-19 15:35 UTC, alexruzenhack commented on src/screens/NetworkSettings/NetworkSettingsDisclaimerScreen.js
> +export function NetworkSettingsDislaimerScreen({ navigation }) {
- Fix typo on disclaimer names: 1078ed2302e99e0d406c104a503e3f84141b1933

2023-10-19 15:35 UTC, alexruzenhack commented on src/screens/NetworkSettings/NetworkSettingsDisclaimerScreen.js
> +            {t`Do not change this unless you know what your are doing, and under no circustance change this settings based on someone else suggestion, as this can potentially make you susceptible to
- Fix typo on message: a193f82fd68984f3745130905184011584bcad03

2023-10-20 02:56 UTC, pedroferreira1 approved these changes

2023-10-20 13:35 UTC, andreabadesso approved these changes

2023-10-25 22:10 UTC, merged