fix: network settings
HathorNetwork/hathor-wallet-mobile pull request #461
Opened 2024-04-05 21:23 UTC by alexruzenhack

### Acceptance Criteria
- Should add a scroll for custom network settings form, to avoid overflow of elements in the screen
- Should add form validation for wallet-service fields, to avoid errors on saga processing

### Security Checklist
- [x] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2024-04-08 22:59 UTC, andreabadesso requested changes

2024-04-08 22:59 UTC, andreabadesso commented on src/screens/NetworkSettings/CustomNetworkSettingsScreen.js
> +      style={{ flex: 1 }}
Add to styles

2024-04-08 22:59 UTC, andreabadesso commented on src/screens/NetworkSettings/CustomNetworkSettingsScreen.js
> +        {hasSucceed(networkSettingsStatus) && (
```suggestion
        {hasSucceeded(networkSettingsStatus) && (
```

2024-04-08 22:59 UTC, andreabadesso commented on src/screens/NetworkSettings/CustomNetworkSettingsScreen.js
> +            text={feedbackSucceedText}
```suggestion
            text={feedbackSucceededText}
```

2024-04-08 23:02 UTC, pedroferreira1 approved these changes

2024-04-09 15:31 UTC, alexruzenhack commented on src/screens/NetworkSettings/CustomNetworkSettingsScreen.js
> +        {hasSucceed(networkSettingsStatus) && (
Fixed

2024-04-09 15:33 UTC, alexruzenhack commented on src/screens/NetworkSettings/CustomNetworkSettingsScreen.js
> +      style={{ flex: 1 }}
Added

2024-04-09 18:59 UTC, andreabadesso approved these changes

2024-04-09 19:45 UTC, merged