fix: txMiningServiceUrl lack of declaration on customNetwork
HathorNetwork/hathor-wallet-mobile pull request #503
Opened 2024-07-01 20:15 UTC by alexruzenhack

### Acceptance Criteria
- It should declare `txMiningServiceUrl` on customNetwork payload to update the state on redux store

### Security Checklist
- [x] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2024-07-01 22:09 UTC, pedroferreira1 approved these changes

2024-07-02 13:05 UTC, andreabadesso approved these changes

2024-07-05 03:23 UTC, pedroferreira1 approved these changes

2024-07-05 03:23 UTC, pedroferreira1 commented on src/sagas/networkSettings.js
>      return;
I've been using the following code in the desktop (and in the lib method that will substitute this code here)

```
if (potentialNetwork === NETWORK_MAINNET) {
  network = NETWORK_MAINNET;
} else if (potentialNetwork.includes(NETWORK_TESTNET)) {
  network = NETWORK_TESTNET;
} else {
  network = NETWORK_PRIVATENET;
}
```

I think we can continue with your code but there's a small difference and the code I wrote above will substitute this one soon with the lib method.

2024-07-09 12:51 UTC, andreabadesso requested changes

2024-07-09 12:51 UTC, andreabadesso commented on src/sagas/wallet.js
> +  for (const token of registeredUids.filter((token) => token !== htrUid)) {
```suggestion
  for (const token of registeredUids) {
    if (token !== htrUid) continue;
```

2024-07-09 12:51 UTC, andreabadesso commented on src/sagas/tokens.js
> +      log.debug(`Success fetching token balance for token ${tokenId}.`);
```suggestion
      log.debug(`Token balance already downloaded for ${tokenId}. Will not download again.`);
```

2024-07-09 12:51 UTC, andreabadesso commented on src/sagas/tokens.js
> +      log.debug(`Success fetching token history from store for token ${tokenId}.`);
Same here

2024-07-10 13:13 UTC, andreabadesso approved these changes

2024-07-10 16:34 UTC, merged