refactor: replace network identification logic by the lib method
HathorNetwork/hathor-wallet-mobile pull request #534
Opened 2024-08-15 22:42 UTC by alexruzenhack

### Acceptance Criteria
- Replace the network logic on sagas/networkSettings by the lib method getNetworkFromFullNodeNetwork
- Update the lib version to v1.9.0

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2024-08-16 15:09 UTC, andreabadesso requested changes
Did you forget `package.json`?

2024-08-19 16:18 UTC, alexruzenhack commented
> Did you forget `package.json`?

Indeed. Added now.

2024-08-20 03:02 UTC, pedroferreira1 approved these changes

2024-08-22 14:17 UTC, andreabadesso approved these changes

2024-08-22 16:00 UTC, merged